
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: rails_version_development
  username: club_central
  password: ClubCentral85
  host: 127.0.0.1
  port: 5432

test:
  <<: *default
  database: rails_version_test
  username: club_central
  password: ClubCentral85
  host: 127.0.0.1
  port: 5432


production:
  primary:
    <<: *default
    database: rails_version_production
    username: <%= ENV['DATABASE_USERNAME'] %>
    password: <%= ENV['DATABASE_PASSWORD'] %>
    host: <%= ENV['DATABASE_HOST'] %>
    port: <%= ENV['DATABASE_PORT'] || 5432 %>



# psql -h localhost -U club_central -d rails_version_development
# TRUNCATE TABLE users RESTART IDENTITY;

